#!/bin/sh
# Should be provided $(BUILDDIR) from Makefile.

if [ "$#" -ne 1 ]; then
	echo 'usage: ./check-accessibility <dir>' >&2
	exit 1
fi

cd "$1"

# Make sure all images have associated alt text.
if find "$1" -type f -exec grep -n '<img.*/>' '{}' '+' | grep -v '<img.*alt=.*/>'; then
	echo 'All images must have associated alt-text.' >&2
	exit 1
fi
